openapi: 3.0.0
info:
  title: Flight Check-In Step 7
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /check-in:
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/flight.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/passenger.v1.yaml
      parameters:
        - schema:
            type: string
            pattern: '^[A-Z]{2} [1-9]{4}$'
          in: query
          name: flightNumber
      security:
        - API Key: []
  /check-in/passengers:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                checked-in-passenger:
                  value:
                    barcodeData: s0m3numb3r5
                    checkedInStatus: CHECKED_IN
                    seatNumber: A3
                not-checked-in-passenger:
                  value:
                    barcodeData: s0m3numb3r5
                    checkedInStatus: NOT_CHECKED_IN
                    seatNumber: A3
              schema:
                $ref: ../common/models/flight.v1.yaml
      parameters:
        - schema:
            type: string
            pattern: '^[A-Z]{2} [1-9]{4}$'
            minLength: 0
          in: query
          name: flightNumber
          required: true
      security:
        - API Key: []
components:
  securitySchemes:
    API Key:
      name: x-api-key
      type: apiKey
      in: header
